nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin: ['http://localhost:3000', 'http://localhost:3001']
        allow_headers: ['X-Custom-Auth', 'Content-Type', 'Authorization']
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
        expose_headers: ['Link']
        max_age: 3600
        hosts: []
        forced_allow_origin_value: ~
    paths:
        '^/api/':
            allow_origin: ['http://localhost:3000', 'http://localhost:3001']
            allow_headers: ['X-Custom-Auth', 'Content-Type', 'Authorization']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600
