when@dev:
    web_profiler:
        toolbar: false
        intercept_redirects: false

    framework:
        profiler:
            collect_serializer_data: false
            only_exceptions: true

when@test:
    framework:
        profiler: { collect: false }
